### ISSUE TITLE
Crash on /reload in singleplayer world

### ISSUE THREAD

**Issue by Cheos137** [axieum/authme#40]
### Expected behavior

minecraft reloads all datapacks

### Observed/actual behavior

the game crashes

### Steps/models to reproduce

* Enter a singleplayer world
* Execute `/reload`

### Version

1.18.1-2.2.0

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

### Other

```
[Server thread/ERROR]: Encountered an unexpected exception
java.lang.AbstractMethodError: Receiver class me.axieum.mcmod.authme.impl.config.AuthMeConfig$$Lambda$3680/0x0000000800a2a648 does not define or inherit an implementation of the resolved method 'abstract void startDataPackReload(net.minecraft.server.MinecraftServer, net.minecraft.class_6860)' of interface net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents$StartDataPackReload.
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$12(ServerLifecycleEvents.java:90) ~[quilted-fabric-lifecycle-events-.2-SNAPSHOT-c0669b60f7319883.jar:?]
	at org.quiltmc.qsl.resource.loader.api.ResourceLoaderEvents.lambda$static$0(ResourceLoaderEvents.java:44) ~[quilt_resource_loader-1.0.0+1.18.2-SNAPSHOT-96bedcd9e2fb2cb3.jar:?]
	at net.minecraft.server.MinecraftServer.handler$bec000$onReloadResourcesStart(MinecraftServer.java:3824) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29439(MinecraftServer.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_3097.method_29480(class_3097.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_3097.method_13530(class_3097.java:53) ~[client-intermediary.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177) ~[brigadier-1.0.18.jar:?]
	at net.minecraft.class_2170.method_9249(class_2170.java:264) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_14370(class_3244.java:1253) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_31286(class_3244.java:1237) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12048(class_3244.java:1220) ~[client-intermediary.jar:?]
	at net.minecraft.class_2797.method_12115(class_2797.java:30) ~[client-intermediary.jar:?]
	at net.minecraft.class_2797.method_11054(class_2797.java:7) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:808) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:790) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:769) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by axieum** [comment]
Closed in #42
