### ISSUE TITLE
Crashes when clicking on the Multiplayer button

### ISSUE THREAD

**Issue by RuffleSteels** [axieum/authme#90]
### Expected behavior

When I click the Multiplayer button on Minecraft 1.20.1, loaded in Intellij as I am making a fabric mod atm, it crashes with:

```
---- Minecraft Crash Report ----
// Don't do that.

Time: 2023-07-03 12:25:54
Description: mouseClicked event handler

java.lang.NoSuchMethodError: 'net.minecraft.client.gui.tooltip.Tooltip net.minecraft.client.gui.tooltip.Tooltip.method_47407(net.minecraft.text.Text)'
	at net.minecraft.client.gui.screen.multiplayer.MultiplayerScreen.handler$zzb001$authme$init(MultiplayerScreen.java:559)
	at net.minecraft.client.gui.screen.multiplayer.MultiplayerScreen.init(MultiplayerScreen.java)
	at net.minecraft.client.gui.screen.Screen.init(Screen.java:326)
	at net.minecraft.client.MinecraftClient.setScreen(MinecraftClient.java:1010)
	at net.minecraft.client.gui.screen.TitleScreen.onMultiplayerButtonPressed(TitleScreen.java:316)
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget.java:38)
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget.java:65)
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget.java:192)
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement.java:50)
	at net.minecraft.client.gui.screen.TitleScreen.mouseClicked(TitleScreen.java:276)
	at net.minecraft.client.Mouse.method_1611(Mouse.java:94)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:452)
	at net.minecraft.client.Mouse.onMouseButton(Mouse.java:94)
	at net.minecraft.client.Mouse.method_22686(Mouse.java:171)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:101)
	at net.minecraft.client.Mouse.method_22684(Mouse.java:171)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:196)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1160)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:781)
	at net.minecraft.client.main.Main.main(Main.java:227)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.gui.screen.multiplayer.MultiplayerScreen.handler$zzb001$authme$init(MultiplayerScreen.java:559)
	at net.minecraft.client.gui.screen.multiplayer.MultiplayerScreen.init(MultiplayerScreen.java)
	at net.minecraft.client.gui.screen.Screen.init(Screen.java:326)
	at net.minecraft.client.MinecraftClient.setScreen(MinecraftClient.java:1010)
	at net.minecraft.client.gui.screen.TitleScreen.onMultiplayerButtonPressed(TitleScreen.java:316)
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget.java:38)
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget.java:65)
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget.java:192)
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement.java:50)
	at net.minecraft.client.gui.screen.TitleScreen.mouseClicked(TitleScreen.java:276)
	at net.minecraft.client.Mouse.method_1611(Mouse.java:94)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:452)
	at net.minecraft.client.Mouse.onMouseButton(Mouse.java:94)
	at net.minecraft.client.Mouse.method_22686(Mouse.java:171)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:101)
	at net.minecraft.client.Mouse.method_22684(Mouse.java:171)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.screen.TitleScreen
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:452)
	at net.minecraft.client.Mouse.onMouseButton(Mouse.java:94)
	at net.minecraft.client.Mouse.method_22686(Mouse.java:171)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:101)
	at net.minecraft.client.Mouse.method_22684(Mouse.java:171)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:196)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1160)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:781)
	at net.minecraft.client.main.Main.main(Main.java:227)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric
Stacktrace:
	at net.minecraft.client.resource.ResourceReloadLogger.addReloadSection(ResourceReloadLogger.java:51)
	at net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient.java:2160)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:799)
	at net.minecraft.client.main.Main.main(Main.java:227)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
```

### Observed/actual behavior

The game crashes when I clicked the Multiplayer button

### Steps/models to reproduce

Open Minecraft in Intellij with a gradle project
Click Multiplayer Button

### Version

Auth Me v7.0.1+1.20

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by axieum** [comment]
Unable to reproduce in development with your source as discussed on Discord.
